EPOCHS: 7
BATCH_SIZE: 32
NUM_CLASS: 2
EMBEDDING_SIZE: 100
DECODER_HIDDEN_DIM_HAN: 32
ENCODER_HIDDEN_DIM_HAN: 64
HIDDEN_DIM_LSTM: 64
USE_PRETRAINED_EMBEDDING_MATRIX: False
lr: 0.0001
BATCH_SAMPLER: False # it is better to keep this false.
PATH_TO_SAVE_MODEL_HAN: "./Han Models/Model HAN Epoch {}.pt.tar"
PATH_TO_SAVE_VOCAB_HAN: "./Vocabulary/Vocab HAN.pt.tar"
LAST_SAVED_EPOCH_HAN_MODEL: 5